### PR TITLE
fix route restful bug

### PR DESCRIPTION
**Pull request by gdibble**
#80

### CODE REVIEW

**Comment by gdibble** [comment]
hmm :/

**Comment by Marsup** [comment]
You shouldn't ever push a version in a pull request, it's up to the maintainer to decide what's going to be the next version.

**Comment by gdibble** [comment]
yeah true, removed

**Comment by stongo** [comment]
Tested this out and it broke route settings in opposite case, when `restful` is false in plugin options and you set `restful` to true in route plugin options

**Comment by gdibble** [comment]
I see what went into #80 and appreciate the efforts 
Thanks again :)

**Pull request closed without merging**
